### ISSUE TITLE
Schema JSON?

### ISSUE THREAD

**Issue by danielschonfeld** [andimarek/graphql-java#39] opened 2015-10-15 05:49 UTC
I'm not sure if this is an issue or just my lack of understanding.  Is there currently a way to generate a schema JSON file so a client i'd write in JS would validate against the schema i've create on my Java based server?

I think really what i'm asking is if we could add a static string into Introspection called interospectionQuery as appears here:
https://github.com/graphql/graphql-js/blob/a941554fc56d607fecebe2188a7ca8848835c2a8/src/utilities/introspectionQuery.js#L11

Thanks! This is a great library!

**Comment by pasviegas** [comment] 2015-10-15 10:04
This is what you want

```java
public class UpdateSchema {

  private static final ObjectMapper MAPPER = new ObjectMapper();
  private static final String INTROSPECTION_QUERY = "  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        args {\n          ...InputValue\n        }\n        onOperation\n        onFragment\n        onField\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n        }\n      }\n    }\n  }\n";
  private static final GraphQL GRAPHQL = new GraphQL(SchemaDefinition.schema);

  public static void main(String[] args) throws IOException, URISyntaxException {
    MAPPER.enable(SerializationFeature.INDENT_OUTPUT);
    Files.write(jsonSchema(), jsonSchemaFile(), Charsets.UTF_8);
  }

  private static String jsonSchema() throws JsonProcessingException {
    return MAPPER.writeValueAsString(executeQuery());
  }

  private static ExecutionResult executeQuery() {
    return GRAPHQL.execute(INTROSPECTION_QUERY);
  }

}
```

**Comment by danielschonfeld** [comment] 2015-10-15 13:31
@pasviegas not sure i understand.... in particular where does `SchemaDefinition.schema` comes from

Same goes for `jsonSchemaFile()` but that i can figure out on my own what it does and how to write

**Comment by danielschonfeld** [comment] 2015-10-15 13:33
Also currently when I run the `INTROSPECTION_QUERY` against a schema that has no mutation, it results in the following error:

```Exception in thread "main" graphql.GraphQLException: Cannot return null for non-nullable type: [Field{name='mutationType', alias='null', arguments=[], directives=[], selectionSet=SelectionSet{selections=[Field{name='name', alias='null', arguments=[], directives=[], selectionSet=null}]}}]```

**Comment by pasviegas** [comment] 2015-10-15 13:46
So, this is actually from my codebase, `SchemaDefinition.schema` is just where the schema lives and `jsonSchemaFile()` returns the path to the json file I want to write too.

Basically INTROSPECTION_QUERY is a copy from graphql.js, seems to me that the problem is in the differences this port has from handling nulls from the js one.

I have tested with my schema with no mutations and also getting the same issue.

**Comment by tberman** [comment] 2015-10-15 13:49
That is a bug in 1.2. If you use the latest version from bintray you won't have that issue with the introspection query.

**Comment by andimarek** [comment] 2016-01-23 08:19
I'm closing this issue, because as @tberman mentioned the bug is fixed and I don't think that adding a specific query should be part of the library.

Also the solution of just copying the string from graphql-js is I think a very simple solution currently.

**Closed by andimarek** 2016-01-23 08:19 UTC

**Comment by alamothe** [comment] 2022-08-10 23:23
Introspection query is part of the JavaScript GraphQL library: https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L41

What's the logic for it not to be included in the Java library?

**Comment by bbakerman** [comment] 2022-08-15 07:08
See `graphql.introspection.IntrospectionQuery#INTROSPECTION_QUERY`

And also `graphql.introspection.IntrospectionResultToSchema`

**Comment by alamothe** [comment] 2022-08-16 00:43
Apologies on commenting on an ancient issue. Hopefully whoever stumbles upon this in the future by googling will find this info.
