### ISSUE TITLE
GraphQlFloat single vs double precision

### ISSUE THREAD

**Issue by nikolajosipovic** [andimarek/graphql-java#59] opened 2015-12-26 19:26 UTC
Hi Andi,

Reading the GraphQL spec it says:
> The Float scalar type represents signed double‐precision fractional values as specified by IEEE 754. 

but according to `scalars.GraphQLFloat` it accepts single-precision floating point numbers.

Do you think the implementation needs to be updated.

**Comment by xuzb** [comment] 2015-12-30 09:32
FloatValue is implemented with a BigDecimal. So it supports single and double-precision floating point numbers.

**Comment by andimarek** [comment] 2016-01-02 08:06
@xuzb The AST Node `FloatValue` is using `BigDecimal`, but `scalars.GraphQLFloat` is using Float.

So I think @nikolajosipovic is right, it should also support `double` (or only `double`, I'm not sure)

**Comment by andimarek** [comment] 2016-01-23 09:16
I changed the implementation of GraphQLFloat to return double instead float to comply with the spec:

https://github.com/andimarek/graphql-java/commit/3062e2b48503ec02c9e2364d4c063baa798352a4

What do you think? @nikolajosipovic

**Comment by nikolajosipovic** [comment] 2016-01-30 14:42
Hey @andimarek Thanks a lot for doing the update :+1:  and sorry I did not catch time to contribute

**Comment by andimarek** [comment] 2016-01-31 17:51
@nikolajosipovic No problem ... I'm closing this Issue now.

**Closed by andimarek** 2016-01-31 17:51 UTC

**Comment by javierso** [comment] 2020-04-21 00:05
Not sure if this issue is related to the same underlying root cause but i have noticed that library constantly serializes doubles like the following E.G 4.0d  to  the following string in json response "4". Is there a way to modify this behavior
